name: deploy_production

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: copy to server instance
        uses: appleboy/scp-action@v0.1.7
        with:
          source: /home/runner/work/e-portal--server/e-portal--server
          target: /home/parkbritish/api/app/__update
          host: 167.99.139.37
          port: 22
          username: parkbritish
          password: alphabetagamma
      - name: restart account service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 167.99.139.37
          port: 22
          username: parkbritish
          password: alphabetagamma
          script: |
            cd ./api/app
            cp -r ./__update/github/workspace/. .
            npm install
            pm2 restart all
