name: deploy_staging

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: copy files to server
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: /home/runner/work/backend-accounts-service/backend-accounts-service
          remote: staging/backend/services/accounts
          host: 18.196.23.206
          username: ubuntu
          password: alphabetagamma
      - name: restart account service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 18.196.23.206
          port: 22
          username: ubuntu
          password: alphabetagamma
          script: |
            cd ./staging/backend/services/accounts
            npm install
            pm2 restart accounts-service-staging
