name: deploy_production

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: CI=false npm run build
      - run: rm -r /home/runner/work/e-portal--server/e-portal--server/node_modules
      - run: rm -r /home/runner/work/e-portal--server/e-portal--server/.git
      - name: copy files to server
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: /home/runner/work/e-portal--server/e-portal--server
          remote: /home/parkbritish/api/app
          host: 167.99.139.37
          username: parkbritish
          password: alphabetagamma
      - name: restart account service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 167.99.139.37
          port: 22
          username: parkbritish
          password: alphabetagamma
          script: |
            cd /home/parkbritish/api/app
            npm install
            pm2 restart all
